package rheoconnect.entities

enum class RheoMessage {
  FLAG_OFF,
  FLAG_ON_TARGET_FAIL,
  FLAG_ON_TARGET_MATCH,
  PREREQUISITE_FAILED,

  CLIENT_NOT_READY,
  FLAG_NOT_FOUND,
  CORRUPTED_FLAG,
  INVALID_INPUT,
  UNKNOWN_ERROR,
  WRONG_TYPE
}
