# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle
run-name: build.outputs.sum
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
  
    runs-on: ubuntu-latest

    outputs:
      sum: "testing github action output"
      
    steps:
      - uses: actions/checkout@v3

#       - name: Testing PR Checks information
      
#       - name: Set up JDK 11
#         uses: actions/setup-java@v3
#         with:
#           java-version: '11'
#           distribution: 'temurin'
#       - name: Configure AWS Credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
#           aws-secret-access-key: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
#           aws-region: us-west-2
#       - name: Test Coverage
#         uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
#         with:
#           arguments: koverVerify
#           uses: romeovs/lcov-reporter-action@v0.2.16
#       - name: Display Code Coverage
#         uses: romeovs/lcov-reporter-action@v0.2.16
#         with:
#           lcov-file: ./coverage/lcov.info
