# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
  
    runs-on: ubuntu-latest

    outputs:
      sum: "testing github action output"
      
    steps:
      - uses: actions/checkout@v3
      - name: "testing name"
        run: curl \
            -X PATCH \
            -H "Accept\:\ application/vnd.github+json" \
            -H "Authorization:\ Bearer ${{secrets.GITHUB_PAT}}" \
            https://api.github.com/repos/om-parashar/testing_actions/check-runs/${{ toJSON(fromJSON(steps.fetch.outputs.data).jobs.*.id) }} \
            -d '{"name":"mighty_readme","started_at":"2018-05-04T01:14:52Z","status":"completed","conclusion":"success","completed_at":"2018-05-04T01:14:52Z","output":{"title":"Mighty Readme report","summary":"There are 0 failures, 2 warnings, and 1 notices.","text":"You may have some misspelled words on lines 2 and 4. You also may want to add a section in your README about how to install your app.","annotations":[{"path":"README.md","annotation_level":"warning","title":"Spell Checker","message":"Check your spelling for '\''banaas'\''.","raw_details":"Do you mean '\''bananas'\'' or '\''banana'\''?","start_line":2,"end_line":2},{"path":"README.md","annotation_level":"warning","title":"Spell Checker","message":"Check your spelling for '\''aples'\''","raw_details":"Do you mean '\''apples'\'' or '\''Naples'\''","start_line":4,"end_line":4}],"images":[{"alt":"Super bananas","image_url":"http://example.com/images/42"}]}}'

#       - name: Testing PR Checks information
      
#       - name: Set up JDK 11
#         uses: actions/setup-java@v3
#         with:
#           java-version: '11'
#           distribution: 'temurin'
#       - name: Configure AWS Credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
#           aws-secret-access-key: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
#           aws-region: us-west-2
#       - name: Test Coverage
#         uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
#         with:
#           arguments: koverVerify
#           uses: romeovs/lcov-reporter-action@v0.2.16
#       - name: Display Code Coverage
#         uses: romeovs/lcov-reporter-action@v0.2.16
#         with:
#           lcov-file: ./coverage/lcov.info
